const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({URL});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/core.js'),'utf8'),context);
const L=context.Living;
const p={id:'test',title:'Casa São João',city:'São Paulo',state:'SP',price:120.5,cleaningFee:35,guests:4,bedrooms:2,bathrooms:1,images:['https://example.com/a.jpg'],amenities:['Wi-Fi','Piscina'],unavailable:['2030-10-12'],active:true};
const r={id:'EL-1',propertyId:'test',guest:'Teste',guests:2,checkIn:'2030-10-15',checkOut:'2030-10-18',total:396.5,status:'pendente'};
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
test('rejeita datas impossíveis',()=>assert.ok(Number.isNaN(L.timestamp('2030-02-30'))));
test('aceita ano bissexto',()=>assert.ok(Number.isFinite(L.timestamp('2032-02-29'))));
test('conta noites atravessando mês e ano',()=>assert.equal(L.nights('2030-12-30','2031-01-02'),3));
test('rejeita saída igual à entrada',()=>assert.ok(L.validateDates('2030-10-10','2030-10-10','2030-01-01')));
test('rejeita entrada passada',()=>assert.ok(L.validateDates('2020-10-10','2020-10-12')));
test('aceita 366 noites para ano bissexto',()=>assert.equal(L.validateDates('2028-01-01','2029-01-01','2028-01-01'),''));
test('rejeita mais de 366 noites',()=>assert.ok(L.validateDates('2030-01-01','2031-01-03','2030-01-01')));
test('bloqueio manual impede reserva',()=>assert.equal(L.available(p,[],'2030-10-11','2030-10-13'),false));
test('saída não ocupa diária',()=>assert.equal(L.available(p,[],'2030-10-10','2030-10-12'),true));
test('pendência impede sobreposição',()=>assert.equal(L.available(p,[r],'2030-10-16','2030-10-19'),false));
test('troca de hóspedes no dia de saída é permitida',()=>assert.equal(L.available(p,[r],'2030-10-18','2030-10-20'),true));
test('cancelamento libera datas',()=>assert.equal(L.available(p,[{...r,status:'cancelada'}],'2030-10-16','2030-10-18'),true));
test('imóvel pausado não aceita reservas',()=>assert.equal(L.available({...p,active:false},[],'2030-10-20','2030-10-22'),false));
test('preço inclui limpeza uma única vez',()=>assert.equal(L.quote(p,'2030-10-20','2030-10-23').total,396.5));
test('busca ignora acentos',()=>assert.equal(L.search([p],[],{destination:'sao paulo'}).length,1));
test('capacidade limita a busca',()=>assert.equal(L.search([p],[],{guests:5}).length,0));
test('filtro de comodidade',()=>assert.equal(L.search([p],[],{amenity:'Piscina'}).length,1));
test('filtro de preço',()=>assert.equal(L.search([p],[],{maxPrice:100}).length,0));
test('favoritos filtra anúncios',()=>assert.equal(L.search([p],[],{favorites:true},[]).length,0));
test('ordena pelo total com limpeza quando há datas',()=>assert.equal(L.search([p,{...p,id:'cheap',price:100,cleaningFee:200}],[],{checkIn:'2030-10-20',checkOut:'2030-10-22',sort:'price-asc'})[0].id,'test'));
test('escapa texto inserido pelo usuário',()=>assert.equal(L.escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
test('rejeita URL de imagem executável',()=>assert.equal(L.safeImage('javascript:alert(1)'),''));
test('neutraliza fórmulas no CSV',()=>assert.equal(L.csvCell('=1+1'),'"\'=1+1"'));
test('valida formato persistido',()=>assert.equal(L.validState({version:1,revision:0,properties:[p],reservations:[r],favorites:[]}),true));
test('rejeita estado corrompido',()=>assert.equal(Boolean(L.validState({version:1,properties:[]})),false));
test('rejeita reserva órfã',()=>assert.equal(L.validState({version:1,revision:0,properties:[p],reservations:[{...r,propertyId:'missing'}],favorites:[]}),false));
console.log(`${count} testes concluídos.`);
